---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Pull Image
      shell: /usr/local/bin/docker pull kushal7551/calculator:latest

    - name: Run the container
      shell: /usr/local/bin/docker create -it --name Calculator kushal7551/calculator