---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Start Docker Service
      homebrew:
        name: docker
        state: started

    - name: Pull Image
      shell: docker pull kushal7551/calculator:latest

    - name: Run the container
      shell: docker create -it --name Calculator kushal7551/calculator